// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../../types/supabase';

const SUPABASE_URL = "https://xmgqknnqbnzvpxahhrkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtZ3Frbm5xYm56dnB4YWhocmtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzQxOTEsImV4cCI6MjA2NjYxMDE5MX0.XHl8fFML1DoFdotyPaO2yN5Zjgx4twK6HFEkVM5fgqM";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
  }
});