
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../../types/supabase';

const SUPABASE_URL = "https://rrtharegnnfvluhkrtpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJydGhhcmVnbm5mdmx1aGtydHBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4ODg3MDksImV4cCI6MjA1ODQ2NDcwOX0.LdaLg1TTbRJPrF7rSqp8lphdwr3ZNx9zg0WRlip_qSQ";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
  }
});
